# coding: utf-8

# flake8: noqa
"""
    SRF Weather

    SRF Meteo serves weather forecast for over 100'000 locations within Switzerland  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Contact: api@srgssr.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

# import models into model package
from srf_weather.models.day import Day
from srf_weather.models.forecast import Forecast
from srf_weather.models.forecast2 import Forecast2
from srf_weather.models.forecast3 import Forecast3
from srf_weather.models.forecastday import Forecastday
from srf_weather.models.geolocation import Geolocation
from srf_weather.models.geolocation_name import GeolocationName
from srf_weather.models.geolocation_name1 import GeolocationName1
from srf_weather.models.geolocation_names_id import GeolocationNamesID
from srf_weather.models.geolocation_names_obj import GeolocationNamesObj
from srf_weather.models.geolocation_names_search import GeolocationNamesSearch
from srf_weather.models.geolocations_id import GeolocationsID
from srf_weather.models.m400 import M400
from srf_weather.models.min_maxcolor import MinMaxcolor
from srf_weather.models.model60minute import Model60minute
from srf_weather.models.poi_type import PoiType
