# coding: utf-8

"""
    SRF Weather

    SRF Meteo serves weather forecast for over 100'000 locations within Switzerland  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Contact: api@srgssr.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, conlist
from srf_weather.models.day import Day

class Forecast3(BaseModel):
    """
    Forecast3
    """
    day: conlist(Day) = ...
    __properties = ["day"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Forecast3:
        """Create an instance of Forecast3 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in day (list)
        _items = []
        if self.day:
            for _item in self.day:
                if _item:
                    _items.append(_item.to_dict())
            _dict['day'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Forecast3:
        """Create an instance of Forecast3 from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return Forecast3.parse_obj(obj)

        _obj = Forecast3.parse_obj({
            "day": [Day.from_dict(_item) for _item in obj.get("day")] if obj.get("day") is not None else None
        })
        return _obj

